#
# Makefile for the input core drivers.
#

obj-$(CONFIG_SERIO)			+= serio.o
obj-$(CONFIG_SERIO_SERPORT)		+= serport.o
obj-$(CONFIG_SERIO_AMBAKMI)		+= ambakmi.o
obj-$(CONFIG_SERIO_PS2MULT)		+= ps2mult.o
obj-$(CONFIG_SERIO_RAW)			+= serio_raw.o
