# Makefile for the lirc drivers.

obj-$(CONFIG_LIRC_IGORPLUGUSB)	+= lirc_igorplugusb.o
obj-$(CONFIG_LIRC_IMON)		+= lirc_imon.o
obj-$(CONFIG_LIRC_SASEM)	+= lirc_sasem.o
obj-$(CONFIG_LIRC_SERIAL)	+= lirc_serial.o
obj-$(CONFIG_LIRC_SIR)		+= lirc_sir.o
obj-$(CONFIG_LIRC_TTUSBIR)	+= lirc_ttusbir.o
obj-$(CONFIG_LIRC_ZILOG)	+= lirc_zilog.o
